### ISSUE TITLE
See page response

### ISSUE THREAD

**Issue by fiskeben** [tv2-thomas/playgodmode-issues#16]
I would be nice to be able to see the entire page response the same way as single feeds and items.

**Comment by tv2-thomas** [comment]
@fiskeben Har du noe innspill på hvor denne infoen burde ligge? Ettersom all data jeg viser så langt er feed/feeditem basert, så gir det ikke mye mening å klaske hele siden inn i hvert eneste item sin infobox

**Comment by fiskeben** [comment]
Jeg så for meg en sånn lupe-ikon i toppen. Alternativt kan godmode-ikonet nede til høyre vise det?

**Comment by tagptroll1** [comment]
La til Show Page response på alle feed lupene, vet ikke hvor stabil denne er ettersom den er litt hacky.. ute i versjon 0.0.6
