### ISSUE TITLE
[BUG] Cached items don't get updated

### ISSUE THREAD

**Issue by fiskeben** [tv2-thomas/playgodmode-issues#21]
**Describe the bug**
When the API response the values shown by the extension do not update when the API response does.

**To Reproduce**
- Open some element in Godmode and inspect it.
- Make some change in the backend causing the item to change
- Open the element again and compare with API response
- 
**Expected behavior**
Godmode should display the same values as the API response.

**Comment by tv2-thomas** [comment]
V0.0.9, internal caches are completely wiped on navigations. Refreshes should also do this
